---
  - name: "Check if java installed "
   stat:
    path: "{{ download_folder }}/jdk1.8.0_241-amd64"
   register: java_file_stat
   changed_when: false

 - name: "stop the play if java not found"
  fail:
    msg: "{{ download_folder }}/jdk1.8.0_241-amd64  not found"
  when: not java_file_stat.stat.exists

 - name: debug java 
    debug: "msg={{java_file_stat.stat.exists}}"

 - name: Download java
    get_url:
      url: "{{download_url}}"
      dest: "{{download_folder}}"
 - name: instll java
   yum:
     name: "{{download_url}}"  
     state: present
   when: ansible_os_family == "RedHat"
#Env varibale 
 - name: Adding the path in the bashrc files
   lineinfile: 
    dest=/root/.bashrc 
    line='export JAVA_HOME=/usr/java/jdk1.8.0_241-amd64' ,'export PATH=$JAVA_HOME/bin:$PATH
 
-  - name: Source the bashrc file
     shell: source /root/.bashr
